### ISSUE TITLE
Consider switching to a repr with a zero-padded year?

### ISSUE THREAD

**Issue by spencerkclark** [Unidata/netcdftime#19]
xref: https://github.com/pydata/xarray/pull/1252#discussion_r123914548

When encoding datetime-like objects for storage in netCDF files, xarray follows the standard convention (converting dates to a series of numbers representing some time unit since a reference date).  The units are encoded as a string attribute of a variable in a netCDF file, e.g. `'days since 2000-01-01 00:00:00'`.  In the process of constructing this string upon saving the file, [xarray uses the repr of the datetime object stored in the array](https://github.com/spencerkclark/xarray/blob/NetCDFTimeIndex/xarray/conventions/coding.py#L229).  Additionally, xarray's datetime decoding logic [depends on the use of the `pandas.Timestamp` constructor](https://github.com/spencerkclark/xarray/blob/NetCDFTimeIndex/xarray/conventions/coding.py#L150) to assess whether a reference date with a standard calendar (encoded as a string) can be represented using a `Timestamp` object (allowing the time series to be decoded fully without the optional dependency of netCDF4) or needs to be represented using a `netcdftime` object (requiring the optional dependency of netCDF4 to be decoded).

In experimenting with round-tripping arrays containing datetime objects outside the Timestamp-valid range to netCDF files and back to xarray objects within pydata/xarray#1252, the non-zero-padded repr of `netcdftime` objects (used in encoding the dates) and the datetime parser used by pandas in attempting to decode the dates do not always play well together.  See for example:
```
In [1]: import xarray as xr

In [2]: from netcdftime import DatetimeProlepticGregorian

In [3]: da = xr.DataArray([DatetimeProlepticGregorian(1, 1, 1), DatetimeProlepticGregorian(1, 2, 1)])

In [4]: da
Out[4]:
<xarray.DataArray (dim_0: 2)>
array([netcdftime._netcdftime.DatetimeProlepticGregorian(1, 1, 1, 0, 0, 0, 0, -1, 1),
       netcdftime._netcdftime.DatetimeProlepticGregorian(1, 2, 1, 0, 0, 0, 0, -1, 1)], dtype=object)
Dimensions without coordinates: dim_0

In [5]: da.to_dataset(name='time').to_netcdf('test-roundtrip.nc')

In [6]: xr.open_dataset('test-roundtrip.nc')
Out[6]:
<xarray.Dataset>
Dimensions:  (dim_0: 2)
Dimensions without coordinates: dim_0
Data variables:
    time     (dim_0) datetime64[ns] 2001-01-01 2001-02-01
```

Upon closer inspection, one can find that this could be fixed by using a repr with a zero-padded year when encoding the datetimes:
```
In [7]: ds = xr.open_dataset('test-roundtrip.nc', decode_times=False)

In [8]: ds.time
Out[8]:
<xarray.DataArray 'time' (dim_0: 2)>
array([ 0, 31])
Dimensions without coordinates: dim_0
Attributes:
    units:     days since    1-01-01 00:00:00
    calendar:  proleptic_gregorian

In [9]: ds.time.attrs['units'] = 'days since 0001-01-01 00:00:00'

In [10]: xr.decode_cf(ds)
/Users/spencerclark/xarray-dev/xarray/xarray/conventions/coding.py:416: RuntimeWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using dummy netCDF4.datetime objects instead, reason: dates out of range
  result = decode_cf_datetime(example_value, units, calendar)
Out[10]: /Users/spencerclark/xarray-dev/xarray/xarray/conventions/coding.py:435: RuntimeWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using dummy netCDF4.datetime objects instead, reason: dates out of range
  calendar=self.calendar)

<xarray.Dataset>
Dimensions:  (dim_0: 2)
Dimensions without coordinates: dim_0
Data variables:
    time     (dim_0) object 0001-01-01 0001-02-01
```
Would using repr with a zero-padded year possibly make sense for `netcdftime` or should we look for an alternative solution to this issue?

**Comment by shoyer** [comment]
I think we could potentially fix this behavior on the xarray side, but ISO-8601 is pretty clear that all years should have four digits. So I still think this would be a win. Certainly `0001-01-01` is much clearer than `01-01-01`.

**Comment by jswhit** [comment]
I think the fundamental problem is that no one has stepped to maintain a separate netcdftime project. Seems like there is still some work to do before I can disconnect it from netcdf4-python.

**Comment by dopplershift** [comment]
I'm happy to help step up on the infrastructure side (well, in a couple weeks probably), but I'm a little uncomfortable with stepping up fully since I don't have much technical knowledge in the space `netcdftime` is operating. So I'm happy to cut releases and stuff, but I'm not in possession of answers when it comes to solutions to problems.

**Comment by spencerkclark** [comment]
It occurs to me now that a possibly less disruptive solution than altering the current string representation of netcdftime datetimes would be to simply add an `isoformat` method, which we could use in xarray, analogous to [`datetime.datetime.isoformat`](https://docs.python.org/2/library/datetime.html#datetime.date.isoformat) or [`pd.Timestamp.isoformat`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Timestamp.isoformat.html).  Would that be preferred over modifying `__str__`?

**Comment by shoyer** [comment]
I don't think changing the repr/string format would be disruptive. I expect most users would agree that `0001-01-01` is clearer than `1-01-01`.

That said, I have no objections to adding an `isoformat()` method, too.
