### ISSUE TITLE
Use Appveyor for CI on Windows

### ISSUE THREAD

**Issue by jhamman** [Unidata/netcdftime#21]
I think we should probably test this package on windows. I have no experience setting up Appveyor so I'm looking for someone that does and wants to see this package supported on Windows.

**Comment by jhamman** [comment]
closing. @ocefpaf already did this and somehow I missed it.

**Comment by jhamman** [comment]
So, I was kind of right. @ocefpaf did add an Appveyor config but something seems to be keeping it from running on master or on PRs.

**Comment by ocefpaf** [comment]
I used my AppVeyor instance to test it when I sent the PR but I don't think anyone activated it for this repo.

PS: the link in the README, https://ci.appveyor.com/project/jswhit/netcdftime/branch/master, seems to be wrong, maybe @jswhit has the rights to activate AppVeyor here.

**Comment by jhamman** [comment]
I think you are right. I do not have full admin rights here so @jswhit will have to link to Appveyor.

**Comment by jswhit** [comment]
Done

**Comment by jswhit** [comment]
appveyor tests fail, looks like the same issue I just fixed in netcdf4-python (https://github.com/Unidata/netcdf4-python/issues/758)

**Comment by jswhit** [comment]
I fixed appveyor.yml in pull request #22

**Comment by jhamman** [comment]
closed via #22.
